require File.join(__dir__, '..', 'example', 'node_modules', 'expo', 'scripts', 'autolinking')
require File.join(__dir__, '..', 'example', 'node_modules', 'react-native', 'scripts', 'react_native_pods')

ENV['NODE_PATH'] = [
  File.join(__dir__, '..', 'example', 'node_modules'),
  ENV['NODE_PATH'],
].compact.join(':')

platform :ios, '16.4'

root_podspec = File.join(__dir__, '..', 'ReactNativeProseEditor.podspec')
raise "ReactNativeProseEditor root podspec is required for React Native codegen" unless File.file?(root_podspec)

project 'NativeEditorTests.xcodeproj'

install! 'cocoapods', deterministic_uuids: false

prepare_react_native_project!

target 'NativeEditorTestHost' do
  pod 'SVGgh', '~> 1.12.1'
  use_expo_modules!(
    projectRoot: File.join(__dir__, '..', 'example'),
    exclude: ['@apollohg/react-native-rich-text-editor', '@apollohg/react-native-rich-text-editor-code-highlighting'],
  )
  react_native_path = '../example/node_modules/react-native'

  use_react_native!(
    :path => react_native_path,
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => true,
  )

  target 'NativeEditorTests' do
    inherit! :search_paths
    @current_target_definition.autolinking_manager = Expo::AutolinkingManager.new(
      self,
      @current_target_definition,
      projectRoot: File.join(__dir__, '..', 'example'),
      exclude: ['@apollohg/react-native-rich-text-editor', '@apollohg/react-native-rich-text-editor-code-highlighting'],
      testsOnly: true,
    )
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      react_native_path,
      :mac_catalyst_enabled => false,
      :ccache_enabled => ENV['USE_CCACHE'] == '1',
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.4'
        config.build_settings['SWIFT_VERSION'] = '5.9'

        if target.name == 'fmt'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          definitions = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
          definitions = [definitions] unless definitions.is_a?(Array)
          definitions << 'FMT_USE_CONSTEVAL=0' unless definitions.include?('FMT_USE_CONSTEVAL=0')
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions
        end
      end
    end
  end
end
