package com.apollohg.editor
import android.app.Activity
import android.os.Handler
import android.os.Looper
import android.view.inputmethod.EditorInfo
import java.time.Duration
import java.util.concurrent.CountDownLatch
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicReference
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.Robolectric
import org.robolectric.RobolectricTestRunner
import org.robolectric.RuntimeEnvironment
import org.robolectric.Shadows.shadowOf
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
internal class NativeEditorExpoViewControlledUpdateRemoteRefreshTest :
    NativeEditorExpoViewControlledUpdateTestFixture() {
    @Test
    fun `prop update generated by adapter refresh renders remote replace without typing`() {
        val expoContext = testExpoContext(RuntimeEnvironment.getApplication())
        val view = NativeEditorExpoView(expoContext.context, expoContext.appContext)
        val backend = FakeEditorV2Backend()
        val adapter = attachAdapterForViewTest(backend)
        val viewToken = EditorV2Registry.register(adapter)
        val editText = view.richTextView.editorEditText
        try {
            view.onAddonEventForTesting = {}
            view.onEditorUpdateForTesting = {}
            view.onEditorReadyForTesting = {}
            view.onSelectionChangeForTesting = {}
            view.setAttachedToNativeWindowForTesting(true)
            view.setEditorId(viewToken)

            val session = backend.sessions.getValue(adapter.editorId)
            session.text = StringBuilder("Remote replace sync")
            session.revision += 1u
            val update = requireNotNull(adapter.refreshFromRustState(null))
            assertTrue(JSONObject(update).has("selection"))
            assertTrue(JSONObject(update).has("scalarLength"))

            view.setPendingEditorUpdateJson(update)
            view.setPendingEditorUpdateEditorId(viewToken)
            view.setPendingEditorUpdateRevision(1)
            view.applyPendingEditorUpdateIfNeeded()

            assertEquals("Remote replace sync", editText.text?.toString())
        } finally {
            EditorV2Registry.remove(adapter.editorId)
            NativeEditorViewRegistry.unregister(viewToken, view)
        }
    }

    @Test
    fun `a remote commit rebases the view so the next keystroke is not refused`() {
        val activity = Robolectric.buildActivity(Activity::class.java).setup().get()
        val expoContext = testExpoContext(activity, activity)
        val view = NativeEditorExpoView(expoContext.context, expoContext.appContext)
        val backend = FakeEditorV2Backend()
        val adapter = attachAdapterForViewTest(backend)
        val viewToken = EditorV2Registry.register(adapter)
        val payloads = mutableListOf<Map<String, Any>>()
        try {
            bindFocusedViewForTypingTest(activity, view, viewToken, payloads)
            val editText = view.richTextView.editorEditText
            assertTrue(commitBoundText(view, "a"))
            shadowOf(Looper.getMainLooper()).idleFor(Duration.ofMillis(200))

            val session = backend.sessions.getValue(adapter.editorId)
            session.text.append("R")
            session.revision += 1uL
            NativeEditorViewRegistry.rebaseAfterRemoteCommit(adapter.editorId)
            shadowOf(Looper.getMainLooper()).idleFor(Duration.ofMillis(200))

            assertEquals(
                "the remote commit is visible without a JS round trip",
                "aR",
                editText.text.toString()
            )

            backend.calls.clear()
            assertTrue(commitBoundText(view, "b"))
            assertEquals(
                "the rebase means the keystroke is admitted first time",
                1L,
                backend.calls.count { it == "applyNativeIntent" }.toLong()
            )
            assertTrue(editText.text.toString().contains("b"))
        } finally {
            EditorV2Registry.remove(adapter.editorId)
            NativeEditorViewRegistry.unregister(viewToken, view)
        }
    }

    @Test
    fun `only the current native owner consumes a remote commit refresh`() {
        val firstExpoContext = testExpoContext(RuntimeEnvironment.getApplication())
        val secondExpoContext = testExpoContext(RuntimeEnvironment.getApplication())
        val firstView = NativeEditorExpoView(firstExpoContext.context, firstExpoContext.appContext)
        val secondView =
            NativeEditorExpoView(secondExpoContext.context, secondExpoContext.appContext)
        val backend = FakeEditorV2Backend()
        val adapter = attachAdapterForViewTest(backend)
        val viewToken = EditorV2Registry.register(adapter)
        try {
            listOf(firstView, secondView).forEach { view ->
                view.onEditorUpdateForTesting = {}
                view.onAddonEventForTesting = {}
                view.onEditorReadyForTesting = {}
                view.onSelectionChangeForTesting = {}
                view.setAttachedToNativeWindowForTesting(true)
                view.setEditorId(viewToken)
            }
            val session = backend.sessions.getValue(adapter.editorId)
            session.text.append("Remote")
            session.revision += 1uL
            backend.calls.clear()

            NativeEditorViewRegistry.rebaseAfterRemoteCommit(adapter.editorId)
            shadowOf(Looper.getMainLooper()).idleFor(Duration.ofMillis(200))

            assertEquals("", firstView.richTextView.editorEditText.text.toString())
            assertEquals("Remote", secondView.richTextView.editorEditText.text.toString())
            assertEquals(1, backend.calls.count { it == "renderNative" })
        } finally {
            EditorV2Registry.remove(adapter.editorId)
            NativeEditorViewRegistry.unregister(viewToken, firstView)
            NativeEditorViewRegistry.unregister(viewToken, secondView)
        }
    }

    @Test
    fun `controlled push at an already rendered revision keeps newer typed text`() {
        val activity = Robolectric.buildActivity(Activity::class.java).setup().get()
        val expoContext = testExpoContext(activity, activity)
        val view = NativeEditorExpoView(expoContext.context, expoContext.appContext)
        val backend = FakeEditorV2Backend()
        val adapter = attachAdapterForViewTest(backend)
        val viewToken = EditorV2Registry.register(adapter)
        val payloads = mutableListOf<Map<String, Any>>()
        try {
            bindFocusedViewForTypingTest(activity, view, viewToken, payloads)
            val editText = view.richTextView.editorEditText

            assertTrue(commitBoundText(view, "a"))
            shadowOf(Looper.getMainLooper()).idleFor(Duration.ofMillis(200))
            val deliveredRevision = payloads.last()["documentRevision"] as String

            assertTrue(commitBoundText(view, "b"))
            assertEquals("ab", editText.text.toString())

            view.setPendingEditorUpdateJson(atomicRenderUpdateJson("a", deliveredRevision))
            view.setPendingEditorUpdateEditorId(viewToken)
            view.setPendingEditorUpdateRevision(1)
            view.applyPendingEditorUpdateIfNeeded()
            shadowOf(Looper.getMainLooper()).idleFor(Duration.ofMillis(200))

            assertEquals(
                "a superseded push must not rewind the typed character",
                "ab",
                editText.text.toString()
            )
            assertTrue(
                view.imeTraceSnapshotForTypingTest().any {
                    it.startsWith("pendingEditorUpdateSuperseded")
                }
            )
        } finally {
            EditorV2Registry.remove(adapter.editorId)
            NativeEditorViewRegistry.unregister(viewToken, view)
        }
    }

    @Test
    fun `controlled push at equal rendered revision is not superseded`() {
        val activity = Robolectric.buildActivity(Activity::class.java).setup().get()
        val expoContext = testExpoContext(activity, activity)
        val view = NativeEditorExpoView(expoContext.context, expoContext.appContext)
        val backend = FakeEditorV2Backend()
        val adapter = attachAdapterForViewTest(backend)
        val viewToken = EditorV2Registry.register(adapter)
        val payloads = mutableListOf<Map<String, Any>>()
        try {
            bindFocusedViewForTypingTest(activity, view, viewToken, payloads)
            assertTrue(commitBoundText(view, "a"))
            shadowOf(Looper.getMainLooper()).idleFor(Duration.ofMillis(200))
            val revision = payloads.last()["documentRevision"] as String

            view.setPendingEditorUpdateJson(atomicRenderUpdateJson("a", revision))
            view.setPendingEditorUpdateEditorId(viewToken)
            view.setPendingEditorUpdateRevision(3)
            view.applyPendingEditorUpdateIfNeeded()

            assertFalse(
                view.imeTraceSnapshotForTypingTest().any {
                    it.startsWith("pendingEditorUpdateSuperseded")
                }
            )
            assertEquals(0, view.pendingEditorUpdateRevisionForTesting())
        } finally {
            EditorV2Registry.remove(adapter.editorId)
            NativeEditorViewRegistry.unregister(viewToken, view)
        }
    }
}
